import type { PublicMarketingMessages } from './public-marketing-pages-messages.js';

export const publicMarketingMessagesEn = {
  language: 'Language',
  polish: 'Polish',
  english: 'English',
  socialProfiles: 'Social profiles',
  preferencesTitle: 'Email preferences',
  preferencesEyebrow: 'Your privacy and consents',
  preferencesFor: ({ email }) => `Settings for ${email}`,
  scopeAll: 'all marketing messages',
  scopeNamed: ({ scope }) => `“${scope}” consent`,
  scopeIntro: ({ scope }) => `This link applies to: ${scope}.`,
  unsubscribeScope: 'Unsubscribe me from this scope',
  unsubscribeEverything: ({ tenant }) => `Unsubscribe me from everything from ${tenant}`,
  unsubscribeWarning: 'The change takes effect immediately. You can also fine-tune your consents below.',
  consentsTitle: 'Optional consents',
  consentsIntro: 'Select the messages you still want to receive. None of these choices is required.',
  pendingConfirmation: 'Waiting for confirmation from the email we sent.',
  noOptionalConsents: 'This creator has no other active optional consents.',
  savePreferences: 'Save preferences',
  globallyUnsubscribed: ({ tenant }) => `This address is unsubscribed from all marketing messages from ${tenant}.`,
  preferencesSavedTitle: 'Preferences saved',
  preferencesSavedBody: 'Your settings have been updated.',
  preferencesPendingBody: 'We will send a confirmation link for each newly selected consent.',
  unsubscribedTitle: 'Unsubscribe confirmed',
  unsubscribedScopeBody: ({ scope }) => `You will no longer receive messages covered by: ${scope}.`,
  unsubscribedAllBody: ({ tenant }) => `You will no longer receive any marketing messages from ${tenant}.`,
  resubscribeHint: 'If you change your mind, you can quietly return and select optional consents again.',
  backToPreferences: 'Back to preferences',
  legalEyebrow: 'Legal document',
  immutableVersion: ({ version, date }) => `This is immutable version ${version}, published on ${date}.`,
  confirmationEyebrow: 'Consent confirmation',
  confirmationPromptTitle: 'Confirm your subscription',
  confirmationPromptBody: ({ tenant }) => `Confirm that you want to receive messages from ${tenant}.`,
  confirmationSubmit: 'Confirm subscription',
  confirmationSuccessTitle: 'Email address confirmed',
  confirmationSuccessBody: ({ tenant }) => `Your consent to messages from ${tenant} is now active.`,
  confirmationExpiredTitle: 'This link is no longer active',
  confirmationExpiredBody: 'The confirmation link has expired or is invalid. Ask the creator to subscribe you to the selected communication again.',
} satisfies PublicMarketingMessages;
