import type { PublicMarketingMessages } from './public-marketing-pages-messages.js';

export const publicMarketingMessagesPl = {
  signupEyebrow: 'Bądźmy w kontakcie',
  signupEmail: 'Adres e-mail',
  signupName: 'Wyświetlana nazwa (opcjonalnie)',
  signupSubmit: 'Zapisuję się',
  signupThanks: 'Dziękujemy za zapis',
  signupPending: 'Sprawdź skrzynkę odbiorczą i potwierdź adres e-mail, aby dokończyć zapis.',

  language: 'Język',
  polish: 'Polski',
  english: 'English',
  socialProfiles: 'Profile społecznościowe',
  preferencesTitle: 'Preferencje e-mail',
  preferencesEyebrow: 'Twoja prywatność i zgody',
  preferencesFor: ({ email }) => `Ustawienia dla adresu ${email}`,
  scopeAll: 'wszystkie wiadomości marketingowe',
  scopeNamed: ({ scope }) => `zgoda „${scope}”`,
  scopeIntro: ({ scope }) => `Ten link dotyczy: ${scope}.`,
  unsubscribeScope: 'Wypisz mnie z tych wiadomości',
  unsubscribeEverything: ({ tenant }) => `Wypisz mnie ze wszystkiego od ${tenant}`,
  unsubscribeWarning: 'Zmiana zadziała od razu. Poniżej możesz też wybrać, które zgody zostawić.',
  consentsTitle: 'Opcjonalne zgody',
  consentsIntro: 'Zaznacz wiadomości, które nadal chcesz otrzymywać. Żadne pole nie jest obowiązkowe.',
  pendingConfirmation: 'Czeka na potwierdzenie — sprawdź skrzynkę e-mail.',
  noOptionalConsents: 'Ten twórca nie oferuje innych opcjonalnych zgód.',
  savePreferences: 'Zapisz preferencje',
  globallyUnsubscribed: ({ tenant }) => `Adres jest wypisany ze wszystkich wiadomości marketingowych od ${tenant}.`,
  preferencesSavedTitle: 'Preferencje zapisane',
  preferencesSavedBody: 'Twoje ustawienia zostały zaktualizowane.',
  preferencesPendingBody: 'Dla nowo zaznaczonych zgód wyślemy e-mail z linkiem potwierdzającym.',
  unsubscribedTitle: 'Wypisanie potwierdzone',
  unsubscribedScopeBody: ({ scope }) => `Wypisaliśmy Cię: ${scope}.`,
  unsubscribedAllBody: ({ tenant }) => `Nie będziesz już otrzymywać żadnych wiadomości marketingowych od ${tenant}.`,
  resubscribeHint: 'Jeśli zmienisz zdanie, wróć tutaj i zaznacz zgody ponownie.',
  backToPreferences: 'Wróć do preferencji',
  legalEyebrow: 'Dokument prawny',
  immutableVersion: ({ version, date }) => `Wersja ${version}, opublikowana ${date}. Treść tej wersji nie ulega zmianie.`,
  confirmationEyebrow: 'Potwierdzenie zgody',
  confirmationPromptTitle: 'Potwierdź zgodę',
  confirmationPromptBody: ({ tenant }) => `Potwierdź, że chcesz otrzymywać wiadomości od ${tenant}.`,
  confirmationSubmit: 'Potwierdzam zgodę',
  confirmationSuccessTitle: 'Zgoda potwierdzona',
  confirmationSuccessBody: ({ tenant }) => `Zgoda na wiadomości od ${tenant} jest teraz aktywna.`,
  confirmationExpiredTitle: 'Link nie jest już aktywny',
  confirmationExpiredBody: 'Link potwierdzający wygasł albo jest nieprawidłowy. Zapisz się ponownie, a wyślemy nowy link.',
} satisfies PublicMarketingMessages;
