import { context, trace } from '@opentelemetry/api';

import { createBetterAuthClientAdapter } from '#adapters/auth/client-adapter.js';
import {
  authConfigQuery,
  apiKeysInvalidates,
  apiKeysQuery,
  apiKeyImportAuditQuery,
  attachModuleMutation,
  bunnyVideosQuery,
  testBunnyConnectionMutation,
  testIfirmaConnectionMutation,
  testKsefConnectionMutation,
  detachModuleMutation,
  deleteLessonMutation,
  deleteLessonAttachmentMutation,
  lessonAttachmentsInvalidates,
  lessonAttachmentsQuery,
  lessonReferencesQuery,
  completeLessonMutation,
  contentHistoryQuery,
  courseStructureQuery,
  coursesInvalidates,
  coursesQuery,
  createApiClient,
  createApiKeyMutation,
  createCourseMutation,
  createCheckoutSessionMutation,
  changePasswordMutation,
  createCouponMutation,
  configureStorageMutation,
  archiveCouponMutation,
  couponStatsQuery,
  couponOptionsQuery,
  couponStatsDetailQuery,
  couponStatsExportQuery,
  couponsInvalidates,
  validateCouponForCheckoutMutation,
  createLessonMutation,
  createModuleMutation,
  createPostMutation,
  createTenantMutation,
  deletePostMutation,
  discussionInvalidates,
  emailSendQuery,
  emailSendsExportQuery,
  emailSendsQuery,
  createEventMutation,
  deleteEventMutation,
  eventIcsQuery,
  eventQuery,
  eventsInvalidates,
  updateEventMutation,
  rsvpEventMutation,
  spaceEventsQuery,
  upcomingEventsQuery,
  discussionQuery,
  devMagicLinkQuery,
  createProductMutation,
  createProductPriceMutation,
  deleteProductDownloadMutation,
  deactivateProductPriceMutation,
  deleteTenantSecretMutation,
  deleteStripeSecretsMutation,
  disableTwoFactorMutation,
  enableTwoFactorMutation,
  grantProductToMemberMutation,
  healthQuery,
  memberGrantsQuery,
  memberCommerceQuery,
  memberTimelineQuery,
  memberEmailSendsQuery,
  schedulerRunQuery,
  schedulerRunsQuery,
  sendSupportMessageMutation,
  setMemberBannedMutation,
  memberGrantsInvalidates,
  memberLearningSummaryQuery,
  memberLearningSummaryInvalidates,
  memberNavigationQuery,
  memberNavigationInvalidates,
  memberHomeFeedQuery,
  memberHomeFeedInvalidates,
  recordTermsConsentMutation,
  resetMemberProgressMutation,
  revokeGrantMutation,
  updateProductAccessItemsMutation,
  productAccessIssuesQuery,
  productDownloadAssetsInvalidates,
  productDownloadAssetsQuery,
  orderReconciliationQuery,
  lessonsInvalidates,
  lessonsQuery,
  markAllNotificationsReadMutation,
  markConversationReadMutation,
  markNotificationReadMutation,
  marketingCampaignActionMutation,
  marketingCampaignQuery,
  marketingCampaignsQuery,
  marketingConsentQuery,
  marketingConsentsQuery,
  marketingDocumentQuery,
  marketingDocumentsQuery,
  marketingInvalidates,
  marketingLayoutsQuery,
  marketingReputationQuery,
  marketingSesIdentitiesQuery,
  marketingSesSettingsQuery,
  pollMarketingSesOnboardingMutation,
  pinPostMutation,
  passkeysInvalidates,
  passkeysQuery,
  reportPostMutation,
  reportsInvalidates,
  reportsQuery,
  resolveReportMutation,
  resolveSignInMethodsMutation,
  provisionMarketingSesMutation,
  startMarketingSesIdentityMutation,
  testMarketingSesSimulatorMutation,
  meInvalidates,
  meQuery,
  updateMyProfileMutation,
  membersQuery,
  membersExportQuery,
  accountSessionsQuery,
  accountSessionsInvalidates,
  revokeAccountSessionMutation,
  revokeOtherAccountSessionsMutation,
  myDataExportQuery,
  myErasureRequestQuery,
  requestMyErasureMutation,
  cancelMyErasureRequestMutation,
  erasureRequestsQuery,
  rejectErasureRequestMutation,
  membersInvalidates,
  modulesInvalidates,
  modulesQuery,
  muteThreadMutation,
  myProductsInvalidates,
  myProductsQuery,
  nextLessonQuery,
  conversationQuery,
  conversationsQuery,
  messagesInvalidates,
  notificationsInvalidates,
  notificationsPageQuery,
  notificationsQuery,
  sendMessageMutation,
  startConversationMutation,
  unreadMessagesQuery,
  createMarketingCampaignMutation,
  createMarketingConsentMutation,
  createMarketingDocumentMutation,
  previewMarketingAudienceMutation,
  publishMarketingDocumentMutation,
  saveMarketingLayoutMutation,
  scheduleMarketingCampaignMutation,
  testMarketingCampaignMutation,
  updateMarketingCampaignMutation,
  updateMarketingConsentMutation,
  updateMarketingDocumentMutation,
  updateMarketingSesSettingsMutation,
  unreadNotificationsQuery,
  postsSearchQuery,
  productsInvalidates,
  productPricesQuery,
  productPricesInvalidates,
  uploadProductDownloadMutation,
  uploadCourseCoverMutation,
  uploadProductCoverMutation,
  uploadBrandingAssetMutation,
  publicOfferInvalidates,
  publicCourseStructureQuery,
  publicNavigationQuery,
  publicOfferQuery,
  publicPaymentConfigQuery,
  publicSpaceEventQuery,
  publicSpaceEventsQuery,
  publicSpaceFeedQuery,
  publicSpaceThreadQuery,
  productsQuery,
  probeStorageMutation,
  ordersQuery,
  orderQuery,
  issueInvoiceMutation,
  refreshInvoiceMutation,
  memberBillingOrdersQuery,
  ordersExportQuery,
  salesSummaryQuery,
  publishProductMutation,
  unpublishProductMutation,
  updateProductMutation,
  spacesQuery,
  staffSpacesQuery,
  createSpaceMutation,
  updateSpaceMutation,
  archiveSpaceMutation,
  spaceFeedQuery,
  followSpaceMutation,
  unfollowSpaceMutation,
  markSpaceSeenMutation,
  reactToPostMutation,
  unreactToPostMutation,
  spacesInvalidates,
  registerPasskeyMutation,
  regenerateBackupCodesMutation,
  requestMagicLinkMutation,
  sendVerificationEmailMutation,
  removeMemberMutation,
  removePasskeyMutation,
  requestPasswordResetMutation,
  resetPasswordMutation,
  revokeApiKeyMutation,
  signInMutation,
  signInWithGoogleMutation,
  signInWithPasskeyMutation,
  signOutMutation,
  signUpMutation,
  simulatePurchaseMutation,
  setTenantSecretMutation,
  configureStripeMutation,
  subscribeThreadMutation,
  tenantSecretsQuery,
  tenantSecretsInvalidates,
  testIntegrationMutation,
  tenantSettingsQuery,
  tenantRoutingQuery,
  updateTenantSettingsMutation,
  tenantSettingsInvalidates,
  onboardingQuery,
  dismissOnboardingMutation,
  onboardingInvalidates,
  tenantSetupReadinessQuery,
  updateCourseMutation,
  updateLessonMutation,
  uploadLessonAttachmentMutation,
  updateModuleMutation,
  updatePostMutation,
  studentCourseInvalidates,
  studentCoursesQuery,
  uncompleteLessonMutation,
  studentLessonQuery,
  studentLessonAttachmentsQuery,
  studentProgressQuery,
  tenantsQuery,
  updateLastViewedMutation,
  verifyTotpMutation,
  verifyBackupCodeMutation,
} from '#core/client/index.js';
import type {
  DiscussionGetInput,
  OrdersExportQueryInput,
  OrdersListQueryInput,
  CouponStatsExportQueryInput,
  CouponStatsQueryInput,
  EmailSendsExportQueryInput,
  EmailSendsQueryInput,
  EventsBySpaceInput,
  SchedulerRunsQueryInput,
  MemberHomeFeedGetInput,
  PostsSearchInput,
  PublicSpaceEventInput,
  PublicSpaceThreadGetInput,
  ReportsListInput,
  SpaceFeedGetInput,
} from '#core/contract/index.js';
import type { MemberExportFormat } from '#core/domain/index.js';

/**
 * W3C `traceparent` for the active span, formatted from the OTel facade so FE→BE
 * trace unification is a one-place binding here. Absent (clean no-op) whenever
 * no tracing context is active — the SDK-free default on both deploy targets.
 */
const traceparent = (): string | undefined => {
  const spanContext = trace.getSpanContext(context.active());
  if (!spanContext) return undefined;
  const flags = spanContext.traceFlags.toString(16).padStart(2, '0');
  return `00-${spanContext.traceId}-${spanContext.spanId}-${flags}`;
};

/** Same-origin: the SPA is always served from the tenant's own domain. */
const apiClient = createApiClient({ baseUrl: '', traceparent });
const authClient = createBetterAuthClientAdapter('');

/**
 * The one binding site. Core/client action factories are bound to their
 * transport (ApiClient, AuthClientPort) exactly once here; features import
 * these ready actions and never see a client, a port or an adapter.
 */
export const actions = {
  health: healthQuery(apiClient),
  me: meQuery(apiClient),
  meInvalidates,
  updateMyProfile: updateMyProfileMutation(apiClient),
  memberBillingOrders: memberBillingOrdersQuery(apiClient),
  publicOffer: publicOfferQuery(apiClient),
  publicOfferInvalidates,
  publicNavigation: publicNavigationQuery(apiClient),
  publicCourseStructure: (courseId: string) => publicCourseStructureQuery(apiClient, courseId),
  publicSpaceFeed: (input: SpaceFeedGetInput) => publicSpaceFeedQuery(apiClient, input),
  publicSpaceThread: (input: PublicSpaceThreadGetInput) => publicSpaceThreadQuery(apiClient, input),
  publicSpaceEvents: (input: EventsBySpaceInput) => publicSpaceEventsQuery(apiClient, input),
  publicSpaceEvent: (input: PublicSpaceEventInput) => publicSpaceEventQuery(apiClient, input),
  publicPaymentConfig: publicPaymentConfigQuery(apiClient),
  createCheckoutSession: createCheckoutSessionMutation(apiClient),
  validateCouponForCheckout: validateCouponForCheckoutMutation(apiClient),
  recordTermsConsent: recordTermsConsentMutation(apiClient),
  authConfig: authConfigQuery(apiClient),
  resolveSignInMethods: resolveSignInMethodsMutation(apiClient),
  tenants: tenantsQuery(apiClient),
  createTenant: createTenantMutation(apiClient),
  products: productsQuery(apiClient),
  createProduct: createProductMutation(apiClient),
  productPrices: (productId: string) => productPricesQuery(apiClient, productId),
  createProductPrice: createProductPriceMutation(apiClient),
  deactivateProductPrice: deactivateProductPriceMutation(apiClient),
  productPricesInvalidates,
  productDownloadAssets: (productId: string) => productDownloadAssetsQuery(apiClient, productId),
  productDownloadAssetsInvalidates,
  uploadProductDownload: uploadProductDownloadMutation(apiClient),
  uploadCourseCover: uploadCourseCoverMutation(apiClient),
  uploadProductCover: uploadProductCoverMutation(apiClient),
  uploadBrandingAsset: uploadBrandingAssetMutation(apiClient),
  deleteProductDownload: deleteProductDownloadMutation(apiClient),
  publishProduct: publishProductMutation(apiClient),
  unpublishProduct: unpublishProductMutation(apiClient),
  updateProduct: updateProductMutation(apiClient),
  updateProductAccessItems: updateProductAccessItemsMutation(apiClient),
  productAccessIssues: productAccessIssuesQuery(apiClient),
  productsInvalidates,
  orders: (input: OrdersListQueryInput) => ordersQuery(apiClient, input),
  orderReconciliation: orderReconciliationQuery(apiClient),
  order: (id: string) => orderQuery(apiClient, id),
  issueInvoice: issueInvoiceMutation(apiClient),
  refreshInvoice: refreshInvoiceMutation(apiClient),
  ordersExport: (input: OrdersExportQueryInput) => ordersExportQuery(apiClient, input),
  salesSummary: salesSummaryQuery(apiClient),
  couponStats: (input: CouponStatsQueryInput) => couponStatsQuery(apiClient, input),
  couponOptions: couponOptionsQuery(apiClient),
  couponStatsDetail: (id: string) => couponStatsDetailQuery(apiClient, id),
  couponStatsExport: (input: CouponStatsExportQueryInput) => couponStatsExportQuery(apiClient, input),
  createCoupon: createCouponMutation(apiClient),
  archiveCoupon: archiveCouponMutation(apiClient),
  couponsInvalidates,
  myProducts: myProductsQuery(apiClient),
  memberNavigation: memberNavigationQuery(apiClient),
  memberNavigationInvalidates,
  memberHomeFeed: (input: MemberHomeFeedGetInput) => memberHomeFeedQuery(apiClient, input),
  memberHomeFeedInvalidates,
  members: membersQuery(apiClient),
  membersExport: (format: MemberExportFormat) => membersExportQuery(apiClient, format),
  accountSessions: accountSessionsQuery(apiClient),
  accountSessionsInvalidates,
  revokeAccountSession: revokeAccountSessionMutation(apiClient),
  revokeOtherAccountSessions: revokeOtherAccountSessionsMutation(apiClient),
  myDataExport: myDataExportQuery(apiClient),
  myErasureRequest: myErasureRequestQuery(apiClient),
  requestMyErasure: requestMyErasureMutation(apiClient),
  cancelMyErasureRequest: cancelMyErasureRequestMutation(apiClient),
  erasureRequests: erasureRequestsQuery(apiClient, {}),
  rejectErasureRequest: rejectErasureRequestMutation(apiClient),
  removeMember: removeMemberMutation(apiClient),
  memberGrants: (memberId: string) => memberGrantsQuery(apiClient, memberId),
  memberCommerce: (memberId: string) => memberCommerceQuery(apiClient, memberId),
  memberTimeline: (memberId: string) => memberTimelineQuery(apiClient, memberId),
  memberLearningSummary: (memberId: string) => memberLearningSummaryQuery(apiClient, memberId),
  resetMemberProgress: resetMemberProgressMutation(apiClient),
  grantProductToMember: grantProductToMemberMutation(apiClient),
  revokeGrant: revokeGrantMutation(apiClient),
  memberGrantsInvalidates,
  memberLearningSummaryInvalidates,
  membersInvalidates,
  setMemberBanned: setMemberBannedMutation(apiClient),
  courses: coursesQuery(apiClient),
  createCourse: createCourseMutation(apiClient),
  updateCourse: updateCourseMutation(apiClient),
  contentHistory: (input: { courseId: string; limit?: number }) =>
    contentHistoryQuery(apiClient, input),
  coursesInvalidates,
  modules: modulesQuery(apiClient),
  createModule: createModuleMutation(apiClient),
  updateModule: updateModuleMutation(apiClient),
  attachModule: attachModuleMutation(apiClient),
  detachModule: detachModuleMutation(apiClient),
  modulesInvalidates,
  lessons: lessonsQuery(apiClient),
  createLesson: createLessonMutation(apiClient),
  updateLesson: updateLessonMutation(apiClient),
  lessonReferences: (lessonId: string) => lessonReferencesQuery(apiClient, lessonId),
  lessonAttachments: (lessonId: string) => lessonAttachmentsQuery(apiClient, lessonId),
  lessonAttachmentsInvalidates,
  uploadLessonAttachment: uploadLessonAttachmentMutation(apiClient),
  deleteLessonAttachment: deleteLessonAttachmentMutation(apiClient),
  deleteLesson: deleteLessonMutation(apiClient),
  lessonsInvalidates,
  simulatePurchase: simulatePurchaseMutation(apiClient),
  myProductsInvalidates,
  studentCourses: studentCoursesQuery(apiClient),
  courseStructure: (courseId: string) => courseStructureQuery(apiClient, courseId),
  studentLesson: (lessonId: string) => studentLessonQuery(apiClient, lessonId),
  studentLessonAttachments: (lessonId: string) => studentLessonAttachmentsQuery(apiClient, lessonId),
  nextLesson: (lessonId: string) => nextLessonQuery(apiClient, lessonId),
  studentProgress: (courseId: string) => studentProgressQuery(apiClient, courseId),
  completeLesson: completeLessonMutation(apiClient),
  uncompleteLesson: uncompleteLessonMutation(apiClient),
  updateLastViewed: updateLastViewedMutation(apiClient),
  studentCourseInvalidates,
  discussion: (input: DiscussionGetInput) => discussionQuery(apiClient, input),
  createPost: createPostMutation(apiClient),
  updatePost: updatePostMutation(apiClient),
  deletePost: deletePostMutation(apiClient),
  subscribeThread: subscribeThreadMutation(apiClient),
  muteThread: muteThreadMutation(apiClient),
  postsSearch: (input: PostsSearchInput) => postsSearchQuery(apiClient, input),
  discussionInvalidates,
  spaces: spacesQuery(apiClient),
  staffSpaces: staffSpacesQuery(apiClient),
  createSpace: createSpaceMutation(apiClient),
  updateSpace: updateSpaceMutation(apiClient),
  archiveSpace: archiveSpaceMutation(apiClient),
  spaceFeed: (input: SpaceFeedGetInput) => spaceFeedQuery(apiClient, input),
  followSpace: followSpaceMutation(apiClient),
  unfollowSpace: unfollowSpaceMutation(apiClient),
  markSpaceSeen: markSpaceSeenMutation(apiClient),
  reactToPost: reactToPostMutation(apiClient),
  pinPost: pinPostMutation(apiClient),
  reportPost: reportPostMutation(apiClient),
  reports: (input: ReportsListInput = {}) => reportsQuery(apiClient, input),
  resolveReport: resolveReportMutation(apiClient),
  reportsInvalidates,
  unreactToPost: unreactToPostMutation(apiClient),
  spacesInvalidates,
  signUp: signUpMutation(authClient),
  signIn: signInMutation(authClient),
  requestMagicLink: requestMagicLinkMutation(authClient),
  sendVerificationEmail: sendVerificationEmailMutation(authClient),
  requestPasswordReset: requestPasswordResetMutation(authClient),
  resetPassword: resetPasswordMutation(authClient),
  changePassword: changePasswordMutation(authClient),
  devMagicLink: (email: string) => devMagicLinkQuery(apiClient, email),
  signOut: signOutMutation(authClient),
  registerPasskey: registerPasskeyMutation(authClient),
  passkeys: passkeysQuery(authClient),
  passkeysInvalidates,
  removePasskey: removePasskeyMutation(authClient),
  signInWithPasskey: signInWithPasskeyMutation(authClient),
  enableTwoFactor: enableTwoFactorMutation(authClient),
  verifyTotp: verifyTotpMutation(authClient),
  verifyBackupCode: verifyBackupCodeMutation(authClient),
  disableTwoFactor: disableTwoFactorMutation(authClient),
  regenerateBackupCodes: regenerateBackupCodesMutation(authClient),
  signInWithGoogle: signInWithGoogleMutation(authClient),
  tenantSecrets: tenantSecretsQuery(apiClient),
  apiKeys: apiKeysQuery(apiClient),
  apiKeyImportAudit: (id: string) => apiKeyImportAuditQuery(apiClient, { id, limit: 100 }),
  createApiKey: createApiKeyMutation(apiClient),
  revokeApiKey: revokeApiKeyMutation(apiClient),
  apiKeysInvalidates,
  setTenantSecret: setTenantSecretMutation(apiClient),
  configureStripe: configureStripeMutation(apiClient),
  deleteTenantSecret: deleteTenantSecretMutation(apiClient),
  deleteStripeSecrets: deleteStripeSecretsMutation(apiClient),
  testIntegration: testIntegrationMutation(apiClient),
  probeStorage: probeStorageMutation(apiClient),
  configureStorage: configureStorageMutation(apiClient),
  testIfirmaConnection: testIfirmaConnectionMutation(apiClient),
  testKsefConnection: testKsefConnectionMutation(apiClient),
  bunnyVideos: (input: { search?: string; page?: number }) => bunnyVideosQuery(apiClient, input),
  testBunnyConnection: testBunnyConnectionMutation(apiClient),
  tenantSecretsInvalidates,
  tenantSettings: tenantSettingsQuery(apiClient),
  tenantRouting: tenantRoutingQuery(apiClient),
  sendSupportMessage: sendSupportMessageMutation(apiClient),
  updateTenantSettings: updateTenantSettingsMutation(apiClient),
  tenantSettingsInvalidates,
  onboarding: onboardingQuery(apiClient),
  dismissOnboarding: dismissOnboardingMutation(apiClient),
  onboardingInvalidates,
  tenantSetupReadiness: tenantSetupReadinessQuery(apiClient),
  notifications: notificationsQuery(apiClient),
  notificationsPage: (limit: number) => notificationsPageQuery(apiClient, { limit }),
  unreadNotifications: unreadNotificationsQuery(apiClient),
  markNotificationRead: markNotificationReadMutation(apiClient),
  markAllNotificationsRead: markAllNotificationsReadMutation(apiClient),
  notificationsInvalidates,
  conversations: (limit: number) => conversationsQuery(apiClient, { limit }),
  conversation: (conversationId: string, limit: number) =>
    conversationQuery(apiClient, { conversationId, limit }),
  unreadMessages: unreadMessagesQuery(apiClient),
  startConversation: startConversationMutation(apiClient),
  sendMessage: sendMessageMutation(apiClient),
  markConversationRead: markConversationReadMutation(apiClient),
  messagesInvalidates,
  spaceEvents: (input: EventsBySpaceInput) => spaceEventsQuery(apiClient, input),
  event: (eventId: string) => eventQuery(apiClient, { eventId }),
  upcomingEvents: (limit: number) => upcomingEventsQuery(apiClient, { limit }),
  eventIcs: (eventId: string) => eventIcsQuery(apiClient, { eventId }),
  rsvpEvent: rsvpEventMutation(apiClient),
  createEvent: createEventMutation(apiClient),
  updateEvent: updateEventMutation(apiClient),
  deleteEvent: deleteEventMutation(apiClient),
  eventsInvalidates,
  marketingCampaigns: marketingCampaignsQuery(apiClient),
  marketingCampaign: (id: string) => marketingCampaignQuery(apiClient, id),
  createMarketingCampaign: createMarketingCampaignMutation(apiClient),
  updateMarketingCampaign: updateMarketingCampaignMutation(apiClient),
  scheduleMarketingCampaign: scheduleMarketingCampaignMutation(apiClient),
  marketingCampaignAction: marketingCampaignActionMutation(apiClient),
  testMarketingCampaign: testMarketingCampaignMutation(apiClient),
  previewMarketingAudience: previewMarketingAudienceMutation(apiClient),
  marketingConsents: marketingConsentsQuery(apiClient),
  marketingConsent: (id: string) => marketingConsentQuery(apiClient, id),
  createMarketingConsent: createMarketingConsentMutation(apiClient),
  updateMarketingConsent: updateMarketingConsentMutation(apiClient),
  marketingDocuments: marketingDocumentsQuery(apiClient),
  marketingDocument: (id: string) => marketingDocumentQuery(apiClient, id),
  createMarketingDocument: createMarketingDocumentMutation(apiClient),
  updateMarketingDocument: updateMarketingDocumentMutation(apiClient),
  publishMarketingDocument: publishMarketingDocumentMutation(apiClient),
  marketingLayouts: marketingLayoutsQuery(apiClient),
  saveMarketingLayout: saveMarketingLayoutMutation(apiClient),
  marketingSesSettings: marketingSesSettingsQuery(apiClient),
  marketingSesIdentities: marketingSesIdentitiesQuery(apiClient),
  pollMarketingSesOnboarding: pollMarketingSesOnboardingMutation(apiClient),
  startMarketingSesIdentity: startMarketingSesIdentityMutation(apiClient),
  provisionMarketingSes: provisionMarketingSesMutation(apiClient),
  testMarketingSesSimulator: testMarketingSesSimulatorMutation(apiClient),
  marketingReputation: marketingReputationQuery(apiClient),
  emailSends: (input: EmailSendsQueryInput) => emailSendsQuery(apiClient, input),
  emailSend: (kind: 'transactional' | 'marketing', id: string) => emailSendQuery(apiClient, kind, id),
  emailSendsExport: (input: EmailSendsExportQueryInput) => emailSendsExportQuery(apiClient, input),
  memberEmailSends: (memberId: string) => memberEmailSendsQuery(apiClient, memberId),
  schedulerRuns: (input: SchedulerRunsQueryInput) => schedulerRunsQuery(apiClient, input),
  schedulerRun: (id: string) => schedulerRunQuery(apiClient, id),
  updateMarketingSesSettings: updateMarketingSesSettingsMutation(apiClient),
  marketingInvalidates,
};
