import { context, trace } from '@opentelemetry/api';

import { createBetterAuthClientAdapter } from '@adapters/auth/client-adapter.js';
import {
  authConfigQuery,
  attachModuleMutation,
  detachModuleMutation,
  deleteLessonMutation,
  lessonReferencesQuery,
  completeLessonMutation,
  contentHistoryQuery,
  courseStructureQuery,
  coursesInvalidates,
  coursesQuery,
  createApiClient,
  createCourseMutation,
  createCheckoutSessionMutation,
  createLessonMutation,
  createModuleMutation,
  createTenantMutation,
  devMagicLinkQuery,
  createProductMutation,
  deleteTenantSecretMutation,
  enableTwoFactorMutation,
  grantProductToMemberMutation,
  memberGrantsQuery,
  memberGrantsInvalidates,
  revokeGrantMutation,
  updateProductAccessItemsMutation,
  productAccessIssuesQuery,
  lessonsInvalidates,
  lessonsQuery,
  meQuery,
  membersQuery,
  membersExportQuery,
  membersInvalidates,
  modulesInvalidates,
  modulesQuery,
  myProductsInvalidates,
  myProductsQuery,
  nextLessonQuery,
  productsInvalidates,
  publicOfferQuery,
  publicPaymentConfigQuery,
  productsQuery,
  publishProductMutation,
  registerPasskeyMutation,
  requestMagicLinkMutation,
  removeMemberMutation,
  requestPasswordResetMutation,
  resetPasswordMutation,
  signInMutation,
  signInWithGoogleMutation,
  signInWithPasskeyMutation,
  signOutMutation,
  signUpMutation,
  simulatePurchaseMutation,
  setTenantSecretMutation,
  tenantSecretsQuery,
  tenantSecretsInvalidates,
  testStripeConnectionMutation,
  tenantSettingsQuery,
  updateTenantSettingsMutation,
  tenantSettingsInvalidates,
  updateCourseMutation,
  updateLessonMutation,
  updateModuleMutation,
  studentCourseInvalidates,
  studentCoursesQuery,
  studentLessonQuery,
  studentProgressQuery,
  tenantsQuery,
  updateLastViewedMutation,
  verifyTotpMutation,
} from '@core/client/index.js';
import type { EntityKind, MemberExportFormat } from '@core/domain/index.js';

/**
 * W3C `traceparent` for the active span, formatted from the OTel facade so FE→BE
 * trace unification is a one-place binding here. Absent (clean no-op) whenever
 * no tracing context is active — the SDK-free default on both deploy targets.
 */
const traceparent = (): string | undefined => {
  const spanContext = trace.getSpanContext(context.active());
  if (!spanContext) return undefined;
  const flags = spanContext.traceFlags.toString(16).padStart(2, '0');
  return `00-${spanContext.traceId}-${spanContext.spanId}-${flags}`;
};

/** Same-origin: the SPA is always served from the tenant's own domain. */
const apiClient = createApiClient({ baseUrl: '', traceparent });
const authClient = createBetterAuthClientAdapter('');

/**
 * The one binding site. Core/client action factories are bound to their
 * transport (ApiClient, AuthClientPort) exactly once here; features import
 * these ready actions and never see a client, a port or an adapter.
 */
export const actions = {
  me: meQuery(apiClient),
  publicOffer: publicOfferQuery(apiClient),
  publicPaymentConfig: publicPaymentConfigQuery(apiClient),
  createCheckoutSession: createCheckoutSessionMutation(apiClient),
  authConfig: authConfigQuery(apiClient),
  tenants: tenantsQuery(apiClient),
  createTenant: createTenantMutation(apiClient),
  products: productsQuery(apiClient),
  createProduct: createProductMutation(apiClient),
  publishProduct: publishProductMutation(apiClient),
  updateProductAccessItems: updateProductAccessItemsMutation(apiClient),
  productAccessIssues: productAccessIssuesQuery(apiClient),
  productsInvalidates,
  myProducts: myProductsQuery(apiClient),
  members: membersQuery(apiClient),
  membersExport: (format: MemberExportFormat) => membersExportQuery(apiClient, format),
  removeMember: removeMemberMutation(apiClient),
  memberGrants: (memberId: string) => memberGrantsQuery(apiClient, memberId),
  grantProductToMember: grantProductToMemberMutation(apiClient),
  revokeGrant: revokeGrantMutation(apiClient),
  memberGrantsInvalidates,
  membersInvalidates,
  courses: coursesQuery(apiClient),
  createCourse: createCourseMutation(apiClient),
  updateCourse: updateCourseMutation(apiClient),
  contentHistory: (input: { entityKind: EntityKind; entityId: string; limit?: number }) =>
    contentHistoryQuery(apiClient, input),
  coursesInvalidates,
  modules: modulesQuery(apiClient),
  createModule: createModuleMutation(apiClient),
  updateModule: updateModuleMutation(apiClient),
  attachModule: attachModuleMutation(apiClient),
  detachModule: detachModuleMutation(apiClient),
  modulesInvalidates,
  lessons: lessonsQuery(apiClient),
  createLesson: createLessonMutation(apiClient),
  updateLesson: updateLessonMutation(apiClient),
  lessonReferences: (lessonId: string) => lessonReferencesQuery(apiClient, lessonId),
  deleteLesson: deleteLessonMutation(apiClient),
  lessonsInvalidates,
  simulatePurchase: simulatePurchaseMutation(apiClient),
  myProductsInvalidates,
  studentCourses: studentCoursesQuery(apiClient),
  courseStructure: (courseId: string) => courseStructureQuery(apiClient, courseId),
  studentLesson: (lessonId: string) => studentLessonQuery(apiClient, lessonId),
  nextLesson: (lessonId: string) => nextLessonQuery(apiClient, lessonId),
  studentProgress: (courseId: string) => studentProgressQuery(apiClient, courseId),
  completeLesson: completeLessonMutation(apiClient),
  updateLastViewed: updateLastViewedMutation(apiClient),
  studentCourseInvalidates,
  signUp: signUpMutation(authClient),
  signIn: signInMutation(authClient),
  requestMagicLink: requestMagicLinkMutation(authClient),
  requestPasswordReset: requestPasswordResetMutation(authClient),
  resetPassword: resetPasswordMutation(authClient),
  devMagicLink: (email: string) => devMagicLinkQuery(apiClient, email),
  signOut: signOutMutation(authClient),
  registerPasskey: registerPasskeyMutation(authClient),
  signInWithPasskey: signInWithPasskeyMutation(authClient),
  enableTwoFactor: enableTwoFactorMutation(authClient),
  verifyTotp: verifyTotpMutation(authClient),
  signInWithGoogle: signInWithGoogleMutation(authClient),
  tenantSecrets: tenantSecretsQuery(apiClient),
  setTenantSecret: setTenantSecretMutation(apiClient),
  deleteTenantSecret: deleteTenantSecretMutation(apiClient),
  testStripeConnection: testStripeConnectionMutation(apiClient),
  tenantSecretsInvalidates,
  tenantSettings: tenantSettingsQuery(apiClient),
  updateTenantSettings: updateTenantSettingsMutation(apiClient),
  tenantSettingsInvalidates,
};
