export const CAPABILITIES = [
  'health:read',
  'auth:use',
  'tenant:create',
  'tenant:list-own',
  'tenant:settings:read',
  'tenant:settings:write',
  'tenant:secret:read',
  'tenant:secret:write',
  'tenant:onboarding:read',
  'tenant:onboarding:write',
  'terms:accept',
  'development:inspect',
  'development:mutate',
  'enrollment:create',
  'product:read',
  'product:write',
  'product:publish',
  'product:access:read',
  'product:access:write',
  'product:price:read',
  'product:price:write',
  'member:read',
  'member:commerce:read',
  'member:timeline:read',
  'member:export',
  'member:data-export:self-read',
  'member:erasure:self-request',
  'member:profile:self-write',
  'member:erasure:read',
  'member:remove',
  'member:ban',
  'member:grant:read',
  'member:grant:write',
  'member:learning:read',
  'member:progress:read',
  'member:progress:self-write',
  'member:progress:manage',
  'member:billing:read',
  'member:product:read',
  'api-key:read',
  'api-key:write',
  'course:read',
  'course:write',
  'course:history:read',
  'lesson:play',
  'community:read',
  'community:write',
  'community:moderate',
  'community:pin',
  'community:report',
  'community:report:read',
  'space:read',
  'space:write',
  'space:interact',
  'notification:read',
  'notification:write',
  'dm:read',
  'dm:write',
  'order:read',
  'order:export',
  'order:reconcile',
  'sales:read',
  'support:request',
  'invoice:read',
  'invoice:member-read',
  'invoice:write',
  'coupon:read',
  'coupon:write',
  'coupon:report',
  'integration:test',
  'marketing:consent:read',
  'marketing:consent:write',
  'marketing:consent-definition:read',
  'marketing:consent-definition:write',
  'marketing:campaign:read',
  'marketing:campaign:write',
  'marketing:campaign:send',
  'marketing:campaign:dispatch',
  'marketing:message:read',
  'marketing:message:send',
  'marketing:document:read',
  'marketing:document:write',
  'marketing:layout:read',
  'marketing:layout:write',
  'marketing:ses:read',
  'marketing:ses:write',
  'marketing:suppression:read',
  'marketing:suppression:write',
  'marketing:delivery:read',
  'marketing:reputation:read',
  'transactional:message:read',
  'transactional:message:send',
  'import:content-write',
  'import:users-write',
  'import:validate',
  'scheduler:read',
  'scheduler:dispatch',
  'checkout:read',
  'checkout:start',
  'offer:read',
  'legal:read',
  'webhook:process',
] as const;

export type Capability = (typeof CAPABILITIES)[number];

export const PRINCIPALS = [
  'owner',
  'admin',
  'member',
  'authenticated',
  'api-key',
  'transactional-api-key',
  'import-content-api-key',
  'import-users-api-key',
  'operator-secret',
  'webhook',
  'token',
  'public',
] as const;

export type Principal = (typeof PRINCIPALS)[number];

export type CapabilityMatrix = Record<Principal, readonly Capability[]>;

const VERIFIED_EMAIL_CAPABILITIES: readonly Capability[] = ['tenant:create'];

export const requiresVerifiedEmail = (capability: Capability): boolean =>
  VERIFIED_EMAIL_CAPABILITIES.includes(capability);

const sharedStaffCapabilities = [
  'tenant:create',
  'tenant:list-own',
  'tenant:settings:read',
  'tenant:secret:read',
  'tenant:onboarding:read',
  'tenant:onboarding:write',
  'product:read',
  'product:write',
  'product:publish',
  'product:access:read',
  'product:access:write',
  'product:price:read',
  'product:price:write',
  'member:read',
  'member:commerce:read',
  'member:timeline:read',
  'member:export',
  'member:erasure:read',
  'member:remove',
  'member:ban',
  'member:grant:read',
  'member:grant:write',
  'member:learning:read',
  'member:progress:manage',
  'api-key:read',
  'course:read',
  'course:write',
  'course:history:read',
  'lesson:play',
  'community:read',
  'community:write',
  'community:moderate',
  'community:pin',
  'community:report',
  'community:report:read',
  'space:read',
  'space:write',
  'space:interact',
  'notification:read',
  'notification:write',
  'dm:read',
  'dm:write',
  'order:read',
  'order:export',
  'order:reconcile',
  'sales:read',
  'support:request',
  'invoice:read',
  'invoice:write',
  'coupon:read',
  'coupon:write',
  'coupon:report',
  'marketing:consent-definition:read',
  'marketing:consent-definition:write',
  'marketing:consent:read',
  'marketing:consent:write',
  'marketing:campaign:read',
  'marketing:campaign:write',
  'marketing:campaign:send',
  'marketing:campaign:dispatch',
  'marketing:message:read',
  'marketing:message:send',
  'marketing:document:read',
  'marketing:document:write',
  'marketing:layout:read',
  'marketing:layout:write',
  'marketing:ses:read',
  'marketing:ses:write',
  'marketing:suppression:read',
  'marketing:suppression:write',
  'marketing:delivery:read',
  'marketing:reputation:read',
  'scheduler:read',
  'scheduler:dispatch',
  'webhook:process',
] as const satisfies readonly Capability[];

const ownerOnlyCapabilities = [
  'tenant:settings:write',
  'tenant:secret:write',
  'api-key:write',
  'integration:test',
] as const satisfies readonly Capability[];

export const ROLE_CAPABILITIES: CapabilityMatrix = {
  owner: [...sharedStaffCapabilities, ...ownerOnlyCapabilities],
  admin: sharedStaffCapabilities,
  member: [
    'tenant:create',
    'tenant:list-own',
    'tenant:settings:read',
    'member:progress:self-write',
    'member:progress:read',
    'member:billing:read',
    'member:data-export:self-read',
    'member:erasure:self-request',
    'member:profile:self-write',
    'member:product:read',
    'lesson:play',
    'community:read',
    'community:write',
    'community:report',
    'space:read',
    'space:interact',
    'notification:read',
    'notification:write',
    'dm:read',
    'dm:write',
    'invoice:member-read',
    'support:request',
    'marketing:consent:read',
    'marketing:consent:write',
    'marketing:message:read',
  ],
  authenticated: [
    'tenant:create',
    'tenant:list-own',
    'terms:accept',
    'marketing:consent:read',
    'marketing:consent:write',
    'marketing:message:read',
  ],
  'api-key': [
    'marketing:consent:read',
    'marketing:consent:write',
    'marketing:message:read',
    'marketing:message:send',
    'marketing:layout:read',
    'marketing:suppression:read',
    'marketing:suppression:write',
    'enrollment:create',
  ],
  'transactional-api-key': [
    'transactional:message:read',
    'transactional:message:send',
  ],
  'import-content-api-key': ['import:content-write', 'import:validate'],
  'import-users-api-key': ['import:users-write', 'import:validate'],
  'operator-secret': [
    'scheduler:read',
    'scheduler:dispatch',
    'marketing:campaign:send',
    'marketing:campaign:dispatch',
    'marketing:message:send',
  ],
  webhook: ['webhook:process'],
  token: ['marketing:consent:read', 'marketing:consent:write'],
  public: [
    'health:read',
    'auth:use',
    'marketing:consent:write',
    'marketing:document:read',
    'checkout:read',
    'checkout:start',
    'offer:read',
    'lesson:play',
    'legal:read',
    'development:inspect',
    'development:mutate',
  ],
};

export const capabilitiesForPrincipal = (principal: Principal): readonly Capability[] =>
  ROLE_CAPABILITIES[principal];
