export const CAPABILITIES = [
  'health:read',
  'auth:use',
  'tenant:create',
  'tenant:list-own',
  'tenant:settings:read',
  'tenant:settings:write',
  'tenant:secret:read',
  'tenant:secret:write',
  'tenant:onboarding:read',
  'tenant:onboarding:write',
  'product:read',
  'product:write',
  'product:publish',
  'product:access:read',
  'product:access:write',
  'product:price:read',
  'product:price:write',
  'member:read',
  'member:export',
  'member:remove',
  'member:grant:read',
  'member:grant:write',
  'member:learning:read',
  'member:progress:read',
  'member:progress:self-write',
  'member:progress:manage',
  'member:billing:read',
  'member:product:read',
  'api-key:read',
  'api-key:write',
  'course:read',
  'course:write',
  'course:history:read',
  'lesson:play',
  'community:read',
  'community:write',
  'community:moderate',
  'space:read',
  'space:write',
  'notification:read',
  'notification:write',
  'order:read',
  'order:export',
  'sales:read',
  'invoice:read',
  'invoice:member-read',
  'invoice:write',
  'coupon:read',
  'coupon:write',
  'coupon:report',
  'integration:test',
  'marketing:consent:read',
  'marketing:consent:write',
  'marketing:campaign:read',
  'marketing:campaign:write',
  'marketing:campaign:send',
  'marketing:message:read',
  'marketing:message:send',
  'marketing:document:read',
  'marketing:document:write',
  'marketing:layout:read',
  'marketing:layout:write',
  'marketing:ses:read',
  'marketing:ses:write',
  'marketing:suppression:read',
  'marketing:suppression:write',
  'marketing:delivery:read',
  'marketing:reputation:read',
  'scheduler:read',
  'scheduler:dispatch',
  'checkout:read',
  'checkout:start',
  'offer:read',
  'legal:read',
  'webhook:process',
] as const;

export type Capability = (typeof CAPABILITIES)[number];

export const PRINCIPALS = [
  'owner',
  'admin',
  'member',
  'authenticated',
  'api-key',
  'operator-secret',
  'webhook',
  'token',
  'public',
] as const;

export type Principal = (typeof PRINCIPALS)[number];
