import { z } from 'zod';

import {
  marketingContactListQuerySchema, marketingContactUpsertSchema, marketingContactFieldsSchema, marketingContactPublicSchema, marketingContactPageSchema,
  marketingListSchema, marketingListCreateSchema, marketingListUpdateSchema, marketingListQuerySchema, marketingListPageSchema, marketingListCountsSchema, marketingListMembershipChangeSchema,
  marketingImportUploadSchema, marketingImportRemapSchema, marketingImportCreateSchema, marketingImportAppendSchema, marketingImportCommitSchema, marketingContactImportSchema, marketingImportRowReceiptSchema, marketingImportValidationSchema, marketingDirectoryEventSchema,
} from '#core/domain/index.js';

export { renderMarketingContactCsv, parseMarketingImportCsv, mapMarketingImportCsv, marketingImportMappingSchema, MARKETING_IMPORT_ATTESTATION_VERSION, MARKETING_IMPORT_ATTESTATION_TEXT, MARKETING_DIRECTORY_ATTESTATION_TEXT } from '#core/domain/index.js';
const marketingContactIdSchema = z.object({ contactId: z.string().min(1) }).strict();
const marketingListIdSchema = z.object({ listId: z.string().min(1), consentDefinitionId: z.string().optional() }).strict();
const marketingImportIdSchema = z.object({ importId: z.string().min(1) }).strict();
const marketingContactUpdateRequestSchema = marketingContactFieldsSchema.extend({ contactId: z.string().min(1) });
const marketingListArchiveRequestSchema = z.object({ listId: z.string().min(1), expectedRevision: z.number().int().positive() }).strict();
const marketingListPreviewRequestSchema = marketingListIdSchema.extend({ cursor: z.string().optional(), limit: z.number().int().min(1).max(100).optional() });
const marketingImportRowsQuerySchema = marketingImportIdSchema.extend({ offset: z.number().int().min(0).optional(), limit: z.number().int().min(1).max(200).optional() });
const marketingImportWorkerRequestSchema = z.object({ importId: z.string(), workerId: z.string(), deadlineAt: z.string().datetime(), maxRows: z.number().int().min(1).max(10_000) }).strict();
const marketingMemberSyncRequestSchema = z.object({ deadlineAt: z.string().datetime(), maxJobs: z.number().int().min(1).max(10_000) }).strict();
export const marketingDirectoryContracts = {
  uploadMarketingContactImport: { input: marketingImportUploadSchema, output: marketingImportValidationSchema },
  previewMarketingContactImport: { input: marketingImportRemapSchema, output: marketingImportValidationSchema },
  listMarketingContacts: { input: marketingContactListQuerySchema, output: marketingContactPageSchema },
  exportMarketingContacts: { input: marketingContactListQuerySchema, output: marketingContactPageSchema },
  getMarketingContact: { input: marketingContactIdSchema, output: z.object({ contact: marketingContactPublicSchema, events: z.array(marketingDirectoryEventSchema) }) },
  upsertMarketingContact: { input: marketingContactUpsertSchema, output: z.object({ contact: marketingContactPublicSchema, outcome: z.string() }) },
  updateMarketingContact: { input: marketingContactUpdateRequestSchema, output: z.object({ contact: marketingContactPublicSchema }) },
  archiveMarketingContact: { input: marketingContactIdSchema, output: z.object({ contact: marketingContactPublicSchema }) },
  restoreMarketingContact: { input: marketingContactIdSchema, output: z.object({ contact: marketingContactPublicSchema }) },
  listMarketingLists: { input: marketingListQuerySchema, output: marketingListPageSchema },
  createMarketingList: { input: marketingListCreateSchema, output: z.object({ list: marketingListSchema }) },
  getMarketingList: { input: marketingListIdSchema, output: z.object({ list: marketingListSchema, counts: marketingListCountsSchema }) },
  updateMarketingList: { input: marketingListUpdateSchema, output: z.object({ list: marketingListSchema }) },
  archiveMarketingList: { input: marketingListArchiveRequestSchema, output: z.object({ list: marketingListSchema }) },
  addMarketingListContacts: { input: marketingListMembershipChangeSchema, output: z.object({ changed: z.number() }) },
  removeMarketingListContacts: { input: marketingListMembershipChangeSchema, output: z.object({ changed: z.number() }) },
  previewMarketingList: { input: marketingListPreviewRequestSchema, output: marketingContactPageSchema.extend({ list: marketingListSchema, counts: marketingListCountsSchema }) },
  getMarketingListContacts: { input: marketingListPreviewRequestSchema, output: marketingContactPageSchema.extend({ list: marketingListSchema, counts: marketingListCountsSchema }) },
  createMarketingContactImport: { input: marketingImportCreateSchema, output: z.object({ import: marketingContactImportSchema }) },
  appendMarketingContactImportRows: { input: marketingImportAppendSchema, output: z.object({ import: marketingContactImportSchema }) },
  validateMarketingContactImport: { input: marketingImportIdSchema, output: marketingImportValidationSchema },
  commitMarketingContactImport: { input: marketingImportCommitSchema, output: z.object({ import: marketingContactImportSchema }) },
  getMarketingContactImport: { input: marketingImportIdSchema, output: z.object({ import: marketingContactImportSchema }) },
  getMarketingContactImportRows: { input: marketingImportRowsQuerySchema, output: z.object({ rows: z.array(marketingImportRowReceiptSchema), nextOffset: z.number().nullable() }) },
  retryMarketingContactImport: { input: marketingImportIdSchema, output: z.object({ import: marketingContactImportSchema }) },
  cancelMarketingContactImport: { input: marketingImportIdSchema, output: z.object({ import: marketingContactImportSchema }) },
  importMarketingSuppressions: { input: marketingImportCreateSchema, output: z.object({ import: marketingContactImportSchema }) },
  processMarketingContactImport: { input: marketingImportWorkerRequestSchema, output: z.object({ import: marketingContactImportSchema, processed: z.number() }) },
  syncMarketingMemberContacts: { input: marketingMemberSyncRequestSchema, output: z.object({ processed: z.number(), pending: z.boolean() }) },
} as const;

export const MARKETING_CONTACT_ROUTES = {
  listMarketingContacts: { method: 'GET', path: '/api/marketing/contacts' },
  m2mListMarketingContacts: { method: 'GET', path: '/api/m2m/marketing/contacts' },
  exportMarketingContacts: { method: 'GET', path: '/api/marketing/contacts/export' },
  m2mExportMarketingContacts: { method: 'GET', path: '/api/m2m/marketing/contacts/export' },
  upsertMarketingContact: { method: 'POST', path: '/api/marketing/contacts' },
  m2mUpsertMarketingContact: { method: 'POST', path: '/api/m2m/marketing/contacts' },
  getMarketingContact: { method: 'GET', path: '/api/marketing/contacts/:id' },
  m2mGetMarketingContact: { method: 'GET', path: '/api/m2m/marketing/contacts/:id' },
  updateMarketingContact: { method: 'POST', path: '/api/marketing/contacts/:id/update' },
  m2mUpdateMarketingContact: { method: 'POST', path: '/api/m2m/marketing/contacts/:id/update' },
  archiveMarketingContact: { method: 'POST', path: '/api/marketing/contacts/:id/archive' },
  m2mArchiveMarketingContact: { method: 'POST', path: '/api/m2m/marketing/contacts/:id/archive' },
  restoreMarketingContact: { method: 'POST', path: '/api/marketing/contacts/:id/restore' },
  m2mRestoreMarketingContact: { method: 'POST', path: '/api/m2m/marketing/contacts/:id/restore' },
  listMarketingLists: { method: 'GET', path: '/api/marketing/lists' },
  m2mListMarketingLists: { method: 'GET', path: '/api/m2m/marketing/lists' },
  createMarketingList: { method: 'POST', path: '/api/marketing/lists' },
  m2mCreateMarketingList: { method: 'POST', path: '/api/m2m/marketing/lists' },
  getMarketingList: { method: 'GET', path: '/api/marketing/lists/:id' },
  m2mGetMarketingList: { method: 'GET', path: '/api/m2m/marketing/lists/:id' },
  updateMarketingList: { method: 'POST', path: '/api/marketing/lists/:id/update' },
  m2mUpdateMarketingList: { method: 'POST', path: '/api/m2m/marketing/lists/:id/update' },
  archiveMarketingList: { method: 'POST', path: '/api/marketing/lists/:id/archive' },
  m2mArchiveMarketingList: { method: 'POST', path: '/api/m2m/marketing/lists/:id/archive' },
  addMarketingListContacts: { method: 'POST', path: '/api/marketing/lists/:id/add' },
  m2mAddMarketingListContacts: { method: 'POST', path: '/api/m2m/marketing/lists/:id/add' },
  removeMarketingListContacts: { method: 'POST', path: '/api/marketing/lists/:id/remove' },
  m2mRemoveMarketingListContacts: { method: 'POST', path: '/api/m2m/marketing/lists/:id/remove' },
  previewMarketingList: { method: 'POST', path: '/api/marketing/lists/:id/preview' },
  m2mPreviewMarketingList: { method: 'POST', path: '/api/m2m/marketing/lists/:id/preview' },
  getMarketingListContacts: { method: 'GET', path: '/api/marketing/lists/:id/contacts' },
  m2mGetMarketingListContacts: { method: 'GET', path: '/api/m2m/marketing/lists/:id/contacts' },
  createMarketingContactImport: { method: 'POST', path: '/api/marketing/contact-imports' },
  m2mCreateMarketingContactImport: { method: 'POST', path: '/api/m2m/marketing/contact-imports' },
  appendMarketingContactImportRows: { method: 'POST', path: '/api/marketing/contact-imports/:id/rows' },
  m2mAppendMarketingContactImportRows: { method: 'POST', path: '/api/m2m/marketing/contact-imports/:id/rows' },
  validateMarketingContactImport: { method: 'POST', path: '/api/marketing/contact-imports/:id/validate' },
  m2mValidateMarketingContactImport: { method: 'POST', path: '/api/m2m/marketing/contact-imports/:id/validate' },
  commitMarketingContactImport: { method: 'POST', path: '/api/marketing/contact-imports/:id/commit' },
  m2mCommitMarketingContactImport: { method: 'POST', path: '/api/m2m/marketing/contact-imports/:id/commit' },
  getMarketingContactImport: { method: 'GET', path: '/api/marketing/contact-imports/:id' },
  m2mGetMarketingContactImport: { method: 'GET', path: '/api/m2m/marketing/contact-imports/:id' },
  getMarketingContactImportRows: { method: 'GET', path: '/api/marketing/contact-imports/:id/rows' },
  m2mGetMarketingContactImportRows: { method: 'GET', path: '/api/m2m/marketing/contact-imports/:id/rows' },
  retryMarketingContactImport: { method: 'POST', path: '/api/marketing/contact-imports/:id/retry' },
  m2mRetryMarketingContactImport: { method: 'POST', path: '/api/m2m/marketing/contact-imports/:id/retry' },
  cancelMarketingContactImport: { method: 'POST', path: '/api/marketing/contact-imports/:id/cancel' },
  m2mCancelMarketingContactImport: { method: 'POST', path: '/api/m2m/marketing/contact-imports/:id/cancel' },
  importMarketingSuppressions: { method: 'POST', path: '/api/marketing/suppressions/import' },
  m2mImportMarketingSuppressions: { method: 'POST', path: '/api/m2m/marketing/suppressions/import' },
  processMarketingContactImport: { method: 'POST', path: '/api/marketing/contact-imports/:id/process' },
  m2mProcessMarketingContactImport: { method: 'POST', path: '/api/m2m/marketing/contact-imports/:id/process' },
  syncMarketingMemberContacts: { method: 'POST', path: '/api/marketing/contacts/sync' },
  m2mSyncMarketingMemberContacts: { method: 'POST', path: '/api/m2m/marketing/contacts/sync' },
  marketingContactImportUpload: { method: 'POST', path: '/api/marketing/contact-imports/upload' },
  marketingContactImportPreview: { method: 'POST', path: '/api/marketing/contact-imports/:id/preview' },
  marketingImportsTick: { method: 'GET', path: '/api/internal/marketing/imports/tick' },
} as const;
