minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - brace-expansion@2.1.3
  - smol-toml@1.7.1
  - unbash@4.0.4
  - yoctocolors@2.2.0
onlyBuiltDependencies: []
ignoredBuiltDependencies:
  - esbuild
  - msw
  - unrs-resolver
auditConfig:
  ignoreGhsas:
    - GHSA-67mh-4wv8-2f99
    - GHSA-frvp-7c67-39w9
