import { userEvent, within } from 'storybook/test';
import { useState } from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import { AccountNameFields } from '../features/member/AccountNameFields.js';
import { AccountSupportForm } from '../features/member/AccountSupportForm.js';
import { AccountExportCard } from '../features/member/AccountExportCard.js';
import { AccountErasureCard } from '../features/member/AccountErasureCard.js';
import { AccountCard } from '../features/member/AccountCard.js';
import { EmailLanguagePicker } from '../EmailLanguageSwitcher.js';
import { useToastOutcome } from '../components/ui/Toast.js';
import { useTranslations } from '../i18n/index.js';
import { AccountPanel } from '../theme.js';
import { withAccountPreview, previewFailure } from './page-decorators.js';

const ProfileState = ({ state }: { state: string }) => {
  const t = useTranslations();
  const [name, setName] = useState('Updated demo name');
  const [subject, setSubject] = useState(state === 'SupportSuccess' ? '' : 'Account help');
  const [body, setBody] = useState(state === 'SupportSuccess' ? '' : 'Please help me with my account preferences.');
  const [email, setEmail] = useState('demo@example.com');
  useToastOutcome(state === 'SupportSuccess', t.support.sent, state === 'SupportError' || state === 'NameError' ? t.errors.detailGeneric : null);
  if (state.startsWith('Name')) return <AccountCard title={t.account.profileHeading}><AccountNameFields savedDisplayName="Ada" onCancel={() => setName('Ada')} displayName={name} onChange={setName} error={state === 'NameError' ? previewFailure : null} pending={state === 'NameSaving'} dirty /></AccountCard>;
  if (state.startsWith('Support')) return <AccountSupportForm success={state === 'SupportSuccess'} supportSubject={subject} supportBody={body} onSubjectChange={setSubject} onBodyChange={setBody} error={state === 'SupportError' ? previewFailure : null} pending={state === 'SupportPending'} onSubmit={() => undefined} />;
  if (state.startsWith('Export')) return <AccountExportCard pending={state === 'ExportPreparing'} error={state === 'ExportError' ? previewFailure : null} onDownload={() => undefined} />;
  if (state === 'PreferenceWriteFailure') return <AccountCard title={t.account.languageHeading}><EmailLanguagePicker preference={{ stored: null, storable: true, error: previewFailure, clearError: () => undefined, store: () => undefined }} /></AccountCard>;
  return <AccountPanel><AccountErasureCard request={state === 'ErasureCancelError' ? { id: 'request-demo', tenantId: 'tenant-studio', memberId: 'member-demo', status: 'open', reason: null, requestedAt: '2026-06-20T12:00:00.000Z', dueAt: '2026-07-20T12:00:00.000Z', resolvedAt: null, resolvedByUserId: null, resolutionNote: null } : null} pending={false} error={null} createPending={false} createError={state === 'ErasureCreateError' ? previewFailure : null} cancelPending={false} cancelError={state === 'ErasureCancelError' ? previewFailure : null} email="demo@example.com" erasureConfirmEmail={email} onConfirmEmailChange={setEmail} onCreate={() => undefined} onCancel={() => undefined} onRetry={() => undefined} /></AccountPanel>;
};
const meta = { title: 'Account/ProfileStates', component: ProfileState, decorators: [withAccountPreview] } satisfies Meta<typeof ProfileState>;
export default meta;
type Story = StoryObj<typeof meta>;
const stateStory = (state: string, colorScheme: 'light' | 'dark', viewport: 'desktop' | 'mobile'): Story => ({ args: { state }, parameters: { colorScheme }, globals: { viewport: { value: viewport } }, play: async ({ canvasElement }) => {
  const canvas = within(canvasElement);
  if (state.startsWith('Name')) await userEvent.click(canvas.getByTestId('account-name-open'));
  if (state.startsWith('Support') && state !== 'SupportSuccess') await userEvent.click(canvas.getByTestId('account-support-open'));
  if (state === 'ErasureCreateError') await userEvent.click(canvas.getByTestId('account-erasure-open'));
} });
export const NameDirtyLightDesktop1440: Story = stateStory('NameDirty', 'light', 'desktop');
export const NameDirtyLightMobile390: Story = stateStory('NameDirty', 'light', 'mobile');
export const NameDirtyDarkDesktop1440: Story = stateStory('NameDirty', 'dark', 'desktop');
export const NameDirtyDarkMobile390: Story = stateStory('NameDirty', 'dark', 'mobile');
export const NameSavingLightDesktop1440: Story = stateStory('NameSaving', 'light', 'desktop');
export const NameSavingLightMobile390: Story = stateStory('NameSaving', 'light', 'mobile');
export const NameSavingDarkDesktop1440: Story = stateStory('NameSaving', 'dark', 'desktop');
export const NameSavingDarkMobile390: Story = stateStory('NameSaving', 'dark', 'mobile');
export const NameErrorLightDesktop1440: Story = stateStory('NameError', 'light', 'desktop');
export const NameErrorLightMobile390: Story = stateStory('NameError', 'light', 'mobile');
export const NameErrorDarkDesktop1440: Story = stateStory('NameError', 'dark', 'desktop');
export const NameErrorDarkMobile390: Story = stateStory('NameError', 'dark', 'mobile');
export const PreferenceWriteFailureLightDesktop1440: Story = stateStory('PreferenceWriteFailure', 'light', 'desktop');
export const PreferenceWriteFailureLightMobile390: Story = stateStory('PreferenceWriteFailure', 'light', 'mobile');
export const PreferenceWriteFailureDarkDesktop1440: Story = stateStory('PreferenceWriteFailure', 'dark', 'desktop');
export const PreferenceWriteFailureDarkMobile390: Story = stateStory('PreferenceWriteFailure', 'dark', 'mobile');
export const SupportPendingLightDesktop1440: Story = stateStory('SupportPending', 'light', 'desktop');
export const SupportPendingLightMobile390: Story = stateStory('SupportPending', 'light', 'mobile');
export const SupportPendingDarkDesktop1440: Story = stateStory('SupportPending', 'dark', 'desktop');
export const SupportPendingDarkMobile390: Story = stateStory('SupportPending', 'dark', 'mobile');
export const SupportSuccessLightDesktop1440: Story = stateStory('SupportSuccess', 'light', 'desktop');
export const SupportSuccessLightMobile390: Story = stateStory('SupportSuccess', 'light', 'mobile');
export const SupportSuccessDarkDesktop1440: Story = stateStory('SupportSuccess', 'dark', 'desktop');
export const SupportSuccessDarkMobile390: Story = stateStory('SupportSuccess', 'dark', 'mobile');
export const SupportErrorLightDesktop1440: Story = stateStory('SupportError', 'light', 'desktop');
export const SupportErrorLightMobile390: Story = stateStory('SupportError', 'light', 'mobile');
export const SupportErrorDarkDesktop1440: Story = stateStory('SupportError', 'dark', 'desktop');
export const SupportErrorDarkMobile390: Story = stateStory('SupportError', 'dark', 'mobile');
export const ExportPreparingLightDesktop1440: Story = stateStory('ExportPreparing', 'light', 'desktop');
export const ExportPreparingLightMobile390: Story = stateStory('ExportPreparing', 'light', 'mobile');
export const ExportPreparingDarkDesktop1440: Story = stateStory('ExportPreparing', 'dark', 'desktop');
export const ExportPreparingDarkMobile390: Story = stateStory('ExportPreparing', 'dark', 'mobile');
export const ExportErrorLightDesktop1440: Story = stateStory('ExportError', 'light', 'desktop');
export const ExportErrorLightMobile390: Story = stateStory('ExportError', 'light', 'mobile');
export const ExportErrorDarkDesktop1440: Story = stateStory('ExportError', 'dark', 'desktop');
export const ExportErrorDarkMobile390: Story = stateStory('ExportError', 'dark', 'mobile');
export const ErasureCreateErrorLightDesktop1440: Story = stateStory('ErasureCreateError', 'light', 'desktop');
export const ErasureCreateErrorLightMobile390: Story = stateStory('ErasureCreateError', 'light', 'mobile');
export const ErasureCreateErrorDarkDesktop1440: Story = stateStory('ErasureCreateError', 'dark', 'desktop');
export const ErasureCreateErrorDarkMobile390: Story = stateStory('ErasureCreateError', 'dark', 'mobile');
export const ErasureCancelErrorLightDesktop1440: Story = stateStory('ErasureCancelError', 'light', 'desktop');
export const ErasureCancelErrorLightMobile390: Story = stateStory('ErasureCancelError', 'light', 'mobile');
export const ErasureCancelErrorDarkDesktop1440: Story = stateStory('ErasureCancelError', 'dark', 'desktop');
export const ErasureCancelErrorDarkMobile390: Story = stateStory('ErasureCancelError', 'dark', 'mobile');
export const EnglishMobile: Story = { ...stateStory('NameDirty', 'dark', 'mobile'), parameters: { colorScheme: 'dark', locale: 'en' } };
