import { SCREENS, type ScreenSpec } from './visual-screen-inventory.js';

const pageScreenNames = new Set([
  'anon-home-branded',
  'anon-home-tiles',
  'anon-course',
  'start',
  'start-menu-sheet',
  'search',
  'my-courses',
  'course',
  'my-products',
  'product-stub',
  'account',
  'lesson',
  'community',
  'space-feed',
  'panel-spaces',
  'panel-dashboard',
  'panel-settings-security',
  'panel-settings-redirects',
  'panel-storage-wizard',
  'panel-lesson-attachments',
  'panel-products',
  'panel-product-downloads',
  'panel-coupons',
  'panel-coupon-create',
  'panel-coupon-detail',
  'panel-order-detail',
  'panel-marketing-campaigns',
  'panel-marketing-activity',
  'panel-marketing-activity-detail',
  'panel-marketing-sends',
  'panel-marketing-send-detail',
  'panel-marketing-consents',
  'panel-marketing-documents',
  'panel-marketing-layouts',
  'panel-integrations-email',
  'panel-course',
  'member-detail',
  'member-email-timeline',
]);

export const pageScreens: readonly ScreenSpec[] = SCREENS.filter((screen) => pageScreenNames.has(screen.name));
