import type { BrowserContext, Page } from 'playwright-core';
import { visualRequestPolicy } from './visual-request-policy.js';
const languageStorageKey = 'together-language';
const placeholderPng = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAA8AAAAIcCAYAAAA5Xcd7AAALcUlEQVR4Ae3BAQGAAAwCMKR/zPfQHrLtubs3AAAA8HMNAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAxoAAAAY0AAAAMCABgAAAAY0AAAAMKABAACAAQ0AAAAMaAAAAGBAAwAAAAMaAAAAGNAAAADAgAYAAAAGNAAAADCgAQAAgAENAAAADGgAAABgQAMAAAADGgAAABjQAAAAwIAGAAAABjQAAAAwoAEAAIABDQAAAAxoAAAAYEADAAAAAz4BuQfjJzaLiAAAAABJRU5ErkJggg==',
  'base64',
);

export const stubNonDeterministicRequests = async (context: BrowserContext): Promise<void> => {
  await context.route('**/*', (route) => {
    const policy = visualRequestPolicy(new URL(route.request().url()), route.request().resourceType());
    if (policy === 'abort') return route.abort();
    if (policy === 'continue') return route.continue();
    return route.fulfill({ contentType: 'image/png', body: placeholderPng });
  });
};

export const applyChrome = async (context: BrowserContext): Promise<void> => {
  await context.addInitScript(
    (langKey) => {
      // Capture waits must observe compositor frames even after Playwright installs its clock.
      const nativeFrame = window.requestAnimationFrame.bind(window);
      window.addEventListener('visual:paint-request', () => {
        nativeFrame(() => nativeFrame(() => window.dispatchEvent(new Event('visual:paint-ready'))));
      });
      Object.defineProperty(window, 'EventSource', { configurable: true, value: undefined });
      try {
        window.localStorage.setItem(langKey, 'pl');
      } catch {
        // storage disabled — the choice simply won't persist
      }
    },
    languageStorageKey,
  );
};

export const waitForPaint = async (page: Page): Promise<void> => {
  await page.evaluate(() => new Promise<void>((resolve) => {
    window.addEventListener('visual:paint-ready', () => resolve(), { once: true });
    window.dispatchEvent(new Event('visual:paint-request'));
  }));
};

export const settlePage = async (page: Page, waitForNetworkIdle = true): Promise<void> => {
  if (waitForNetworkIdle) await page.waitForLoadState('networkidle');
  await page.evaluate(async () => {
    await document.fonts.ready;
    await Promise.all([...document.images].filter((image) => !image.complete || image.naturalWidth > 0).map((image) => image.decode()));
  });
  await page.addStyleTag({
    content: `
      *, *::before, *::after {
        animation: none !important;
        transition: none !important;
        caret-color: transparent !important;
      }
    `,
  });
  await waitForPaint(page);
};
