import { marketingContactImportSchema, marketingContactViewSchema, marketingImportRowReceiptSchema, marketingImportValidationSchema, marketingListSchema } from '#core/domain/index.js';

const now = '2026-07-01T12:00:00.000Z';
const contact = marketingContactViewSchema.parse({ id: 'contact-anna', tenantId: 'tenant-studio', email: 'anna@example.org', displayName: 'Anna Example', firstName: null, lastName: null, source: 'import', tags: ['launch', 'news'], memberId: null, createdAt: now, updatedAt: now, archivedAt: null, listKeys: ['newsletter'], consentState: null, suppressionReason: null });
const blocked = { ...contact, id: 'contact-blocked', email: 'blocked@example.org', displayName: 'Blocked Contact', suppressionReason: 'unsubscribe_global' };
const list = marketingListSchema.parse({ id: 'list-newsletter', tenantId: 'tenant-studio', key: 'newsletter', name: 'Newsletter', kind: 'static', rule: null, revision: 1, createdAt: now, updatedAt: now, archivedAt: null });
const dynamic = marketingListSchema.parse({ ...list, id: 'list-launch', key: 'launch', name: 'Launch contacts', kind: 'dynamic', rule: { kind: 'tag', tags: ['launch'], match: 'any' } });
const counts = { contactCount: 2, suppressedCount: 1, eligibleCount: null, consentDefinitionId: null, computedAt: now };
const batch = marketingContactImportSchema.parse({ id: 'import-contacts', tenantId: 'tenant-studio', kind: 'contacts', fileName: 'contacts.csv', fileSha256: null, datasetVersion: 'together-marketing-contacts/v1', mapping: { email: 'email', name: 'name' }, delimiter: ',', defaults: {}, contentHash: 'validated', requestHash: 'request', idempotencyKey: 'test-import', rowCount: 4, consentDefinitionId: 'definition-news', definitionVersion: 1, definitionHash: 'definition', validationHash: 'validated', attestationVersion: null, attestationText: null, attestationLocale: null, attestationNote: null, attestedBy: null, attestedAt: null, invalidRows: 'reject_batch', status: 'ready', resultCounts: {}, lockedBy: null, lockedUntil: null, attempts: 0, nextAttemptAt: now, lastError: null, createdAt: now, startedAt: null, finishedAt: null, stagedDataPurgedAt: null });
const row = marketingImportRowReceiptSchema.parse({ tenantId: 'tenant-studio', importId: batch.id, rowNumber: 1, rowHash: 'row', normalizedEmailHmac: null, stagedPayload: { email: contact.email }, normalizedPayload: { email: contact.email }, status: 'valid', duplicateOf: null, contactId: null, consentRowId: null, suppressionId: null, outcome: null, errors: [], warnings: [], counts: {}, processedAt: null });
const rows = [row, { ...row, rowNumber: 2, normalizedPayload: { email: blocked.email } }, { ...row, rowNumber: 3, status: 'duplicate', duplicateOf: 1 }, { ...row, rowNumber: 4, status: 'invalid', normalizedPayload: null, errors: ['Invalid email'] }];
const preview = marketingImportValidationSchema.parse({ headers: ['email', 'name', 'extra'], canCommitWithSkippedRows: true, previewIssuesLimited: false, import: batch, validationHash: batch.validationHash, preview: rows, counts: { validRows: 2, duplicateRows: 1, rejectedRows: 1, listsToCreate: [] }, errors: [{ rowNumber: 4, message: 'Invalid email' }], warnings: [], canCommit: false });
const suppressionBatch = marketingContactImportSchema.parse({ ...batch, id: 'import-suppressions', kind: 'suppressions', fileName: 'suppressions.csv', mapping: { email: 'email', reason: 'reason', at: 'at' }, defaults: { reason: 'manual', at: now }, consentDefinitionId: null, definitionVersion: null, definitionHash: null, rowCount: 1 });
const suppressionRow = marketingImportRowReceiptSchema.parse({ ...row, importId: suppressionBatch.id, stagedPayload: { email: 'blocked@example.org', reason: 'unsubscribe', at: now }, normalizedPayload: { email: 'blocked@example.org', reason: 'unsubscribe', at: now } });
const suppressionPreview = marketingImportValidationSchema.parse({ headers: ['email', 'reason', 'at'], canCommitWithSkippedRows: true, previewIssuesLimited: false, import: suppressionBatch, validationHash: suppressionBatch.validationHash, preview: [suppressionRow], counts: { validRows: 1, duplicateRows: 0, rejectedRows: 0, listsToCreate: [] }, errors: [], warnings: [], canCommit: true });
const definition = { id: 'definition-news', tenantId: 'tenant-studio', key: 'directory-news', kind: 'optional_marketing', channel: 'email', doubleOptIn: false, documentRef: { mode: 'url', url: 'https://courses.example.org/privacy' }, status: 'active', createdAt: now, updatedAt: now };
const result = (value: unknown) => ({ ok: true, value });
const common = { 'listMarketingConsentDefinitions:[]': result({ definitions: [definition] }), 'listMarketingLists:[]': result({ lists: [list, dynamic], nextCursor: null }) };
const route = '/panel/marketing/contacts/import?importId=import-contacts';
const finalBatch = { ...batch, status: 'completed_with_errors', resultCounts: { ...batch.resultCounts, created: 2, consentBlockedBySuppression: 1, rejectedRows: 1, duplicateRows: 1 }, finishedAt: now };
export const directoryTestFixtures = {
  'panel-marketing-contacts': { route: '/panel/marketing/contacts', calls: { ...common, 'listMarketingContacts:[]': result({ contacts: [contact, blocked], nextCursor: null }) } },
  'panel-marketing-contact-import': { route: '/panel/marketing/contacts/import', calls: common },
  'panel-marketing-contact-preview': { route, calls: { ...common, 'getMarketingContactImport:[]': result({ import: batch }), 'validateMarketingContactImport:[]': result(preview) } },
  'panel-marketing-suppression-preview': { route: '/panel/marketing/contacts/import?importId=import-suppressions', calls: { 'getMarketingContactImport:[]': result({ import: suppressionBatch }), 'validateMarketingContactImport:[]': result(suppressionPreview) } },
  'panel-marketing-contact-queued': { route, calls: { ...common, 'getMarketingContactImport:[]': result({ import: { ...batch, status: 'queued' } }) } },
  'panel-marketing-contact-result': { route, calls: { ...common, 'getMarketingContactImport:[]': result({ import: finalBatch }), 'getMarketingContactImportRows:[]': result({ rows, nextOffset: null }) } },
  'panel-marketing-list-static': { route: '/panel/marketing/lists/list-newsletter', calls: { ...common, 'getMarketingList:[]': result({ list, counts }), 'getMarketingListContacts:[]': result({ list, counts, contacts: [contact, blocked], nextCursor: null }) } },
  'panel-marketing-list-dynamic': { route: '/panel/marketing/lists/list-launch', calls: { ...common, 'getMarketingList:[]': result({ list: dynamic, counts }), 'getMarketingListContacts:[]': result({ list: dynamic, counts, contacts: [contact, blocked], nextCursor: null }) } },
  'panel-marketing-contact-detail': { route: '/panel/marketing/contacts/contact-anna', calls: { ...common, 'getMarketingContact:[]': result({ contact, events: [{ id: 'event-contact-created', tenantId: 'tenant-studio', subjectKind: 'contact', subjectId: contact.id, sequence: 1, type: 'contact_created', actor: 'directory', importId: null, payload: {}, occurredAt: now, createdAt: now }] }), 'listMarketingContacts:[]': result({ contacts: [contact], nextCursor: null }) } },
};
